//
//  RandomName.swift
//  RedCatChat
//
//  Created by Markus Pfeifer on 23.06.21.
//


enum Names {
    
    static func random() -> String {
        names.randomElement()!
    }
    
    private static let names : [String] = [
        "Anthony Baker",
       "Rebecca Campbell",
       "Donald Lewis",
       "Ralph Richardson",
       "Michelle Lopez",
       "George King",
       "Ernest Gonzalez",
       "Andrew Moore",
       "Kevin Martinez",
       "Joan Barnes",
       "Anne Torres",
       "Peter Lee",
       "Roger Clark",
       "David Carter",
       "Jacqueline Williams",
       "Henry Gonzales",
       "Barbara Allen",
       "Cheryl Thomas",
       "John Jones",
       "Adam James",
       "Chris Perry",
       "Albert Kelly",
       "Helen Alexander",
       "Laura Young",
       "Kenneth Morris",
       "Tina Reed",
       "Ruth Russell",
       "Christina Coleman",
       "Jeremy Nelson",
       "Earl Watson",
       "Robert Parker",
       "Rachel Cox",
       "Jonathan Jackson",
       "Emily Howard",
       "Wanda Hill",
       "Jason Bell",
       "Julia Adams",
       "Ruby Price",
       "Bobby Washington",
       "Joseph Morgan",
       "Debra Scott",
       "Margaret Evans",
       "Jean Perez",
       "Beverly Patterson",
       "Christine Miller",
       "Gerald Harris",
       "Lillian Martin",
       "Catherine Taylor",
       "Jesse Gray",
       "Kathy Long",
       "Fred Walker",
       "Thomas Brown",
       "Denise Henderson",
       "Charles Griffin",
       "Jessica Murphy",
       "Alice Turner",
       "Carlos Hughes",
       "Judith Johnson",
       "Brian Hernandez",
       "Shirley Wood",
       "Julie Stewart",
       "Juan Sanders",
       "Benjamin Ward",
       "Deborah Flores",
       "Wayne Powell",
       "Richard Cooper",
       "Carolyn Wright",
       "Lois Wilson",
       "Lisa Bailey",
       "Brenda Foster",
       "Ann Robinson",
       "Todd Collins",
       "Ronald Rodriguez",
       "Walter Simmons",
       "Larry Rivera",
       "Patricia Peterson",
       "Doris Ross",
       "Sean Davis",
       "Justin Rogers",
       "Louis Sanchez",
       "Marilyn Jenkins",
       "Scott Brooks",
       "Nicole Cook",
       "Sarah Thompson",
       "Martha White",
       "Stephanie Smith",
       "Michael Diaz",
       "Lori Green",
       "Patrick Anderson",
       "Frank Ramirez",
       "Linda Hall",
       "Janet Garcia",
       "Dennis Bennett",
       "Tammy Roberts",
       "Gary Phillips",
       "Aaron Butler",
       "Stephen Edwards",
       "Christopher Bryant",
       "Timothy Mitchell",
    ]
    
}
